### ISSUE TITLE
Enigmatic Graves are being culled despite glowing

### ISSUE THREAD

**Issue by BlueAmulet** [tr7zw/EntityCulling-Forge#5]
The graves from EnigmaticGraves are being culled when out of view, but these graves are supposed to glow when the player is holding a specific item.

**Comment by tr7zw** [comment]
Then it's not the vanilla kind of glow. If you can give me the entity name I can add it to the default ignore list, and you can also add it in the config file to bo ignored.

**Comment by BlueAmulet** [comment]
I've found this is because the grave overrides isGlowing to check if the player is holding a certain item, but EntityCulling doesn't call isGlowing and does some weird raw check instead.

The entity is `enigmaticgraves:grave` though, it's an entity not a blockentity though, so it didn't seem like the ignore list would work.

**Comment by tr7zw** [comment]
There is one for blockentities too. Beacons are on that list for example.

**Comment by BlueAmulet** [comment]
Beacons are a block though, the grave is an entity, I don't follow. The entity culling code in CullTask doesn't even look at unCullable

**Comment by tr7zw** [comment]
Ah crap read that it is a block entity. Also looks like in the 1.16 forge version I haven't yet implemented the entity list. (Added it with 1.17 here https://github.com/tr7zw/EntityCulling-Fabric/blob/master/src/main/java/dev/tr7zw/entityculling/EntityCullingMod.java#L34 ) And since Forge still isn't done with their 1.17 update, I haven't looked much in updating the Forge versions.

**Comment by tr7zw** [comment]
This repo is going to be closed and moved over into the Fabric one at https://github.com/tr7zw/EntityCulling .
